<template>
  <div>
    <h1>Közvetítés</h1>
    <iframe
      width="560"
      height="315"
      src="https://www.youtube.com/embed/live_stream?channel=UClZucNJxRAwF26bf6kCWtsQ"
      allowfullscreen
    ></iframe>
  </div>
</template>
